feat: Remake UI to New Design
github-tijlxyz/nostr.cooking pull request #19
Opened 2024-02-07 15:04 UTC by jacany

Full UI Redesign.

UI Concept: https://www.figma.com/file/jrxkv4g3jTXVrE9xW3NJjj/ZapCooking?type=design&node-id=81-1175&mode=design&t=vzZvohlMit4WIOpS-0

2024-02-23 15:54 UTC, jacany commented
BEFORE MERGING: MAKE SURE THAT THE IMAGES COMBO BOX GETS REFACTORED!

2024-02-24 20:51 UTC, jacany commented
A lot of these pages save their content when you navigate, some of them shouldn't.
bookmarks page is an example.

also things like comments don't update when posted, you need to refresh. So that should be fixed too.

2024-02-24 22:08 UTC, jacany commented
Following and unfollowing can't be implemented until nostr-dev-kit/ndk#187 is merged and a version is released.

2024-02-26 15:29 UTC, jacany commented
Honestly, there's a lot of dead code that needs to be trimmed. And MANY optimizations for accessibility and performance need to be made. But the redesign is done!

2024-03-19 20:37 UTC, chakany reviewed
Some things to consider for the future:
- Nostr Connect
- What to do with that onboarding page
- making the recent page it's own special page.
- SSR and prerendering on certain pages.
- NWC
- Low Bandwidth Mode

2024-03-19 20:37 UTC, chakany commented on src/components/Header.svelte
> +              </div>
Remove; nonfunctional.

2024-03-19 20:37 UTC, chakany commented on src/routes/+layout.server.ts
> +export const ssr = false;
May be worth exploring SSR rendering certain pages.

2024-03-19 20:58 UTC, github-tijlxyz requested changes
- we really should support nested comments
 - and also better timestamps for comments
 - this should probably be scrollable and maybe include the icons/emojis ![nostrcooking2](https://github.com/github-tijlxyz/nostr.cooking/assets/123159729/23b06e65-40cd-49dc-8c7a-9484977d4a59)
 - zap modal doesn't really work good on mobile
 - I think you are using `onMount` incorrectly, because sometimes nothing loads after you have been to another page. maybe try using a cache or using $ instead of onMount maybe or something

2024-03-19 21:00 UTC, github-tijlxyz commented on src/routes/+layout.server.ts
> +export const ssr = false;
what exactly, also nostr events?

2024-03-19 21:01 UTC, chakany commented on src/routes/+layout.server.ts
> +export const ssr = false;
categories page for sure.
Maybe it's possible to render nostr events on the recents page? Should probably do the profile page too.

2024-03-19 21:03 UTC, github-tijlxyz commented on src/routes/+layout.server.ts
> +export const ssr = false;
I mean for like a no bandwidth mode we need to create a nostr caching server and a image proxy/caching server I think, because just using the sveltekit SSR also for nostr events isn't gonna work with reasonable performance. But it wouldn't be a nostr client anymore..

2024-03-19 21:03 UTC, github-tijlxyz commented on src/routes/+layout.server.ts
> +export const ssr = false;
But worth considering

2024-03-19 21:06 UTC, chakany commented
> * we really should support nested comments

Why?
> * and also better timestamps for comments

Too relative? Maybe date and time instead?

> * I think you are using `onMount` incorrectly, because sometimes nothing loads after you have been to another page. maybe try using a cache or using $ instead of onMount maybe or something

Will take a look.

2024-03-19 21:32 UTC, github-tijlxyz commented
@chakany 

> Why?

Because people on others clients do have it. and it looks cursed atm

> Too relative? Maybe date and time instead?

I implemented relative timestamps for the comments here, much nicer then the date I think? https://github.com/github-tijlxyz/nostr.cooking/pull/19/commits/65b69dc5ae3e3a864bf921d057fb0bd12a0ab96e

2024-03-20 12:20 UTC, chakany commented
@github-tijlxyz 
> Because people on others clients do have it. and it looks cursed atm

IMO it's not super important, just recipies and I don't see any times when you would need to reply to a comment. Comments are mostly just a fun just cause feature but we can look into it.

> I implemented relative timestamps for the comments here, much nicer then the date I think? [65b69dc](https://github.com/github-tijlxyz/nostr.cooking/commit/65b69dc5ae3e3a864bf921d057fb0bd12a0ab96e)

Oops. Thought it was relative already.

2024-03-21 16:11 UTC, github-tijlxyz commented
@chakany 

I think it is important, its part of the nostr reply spec thing.
And since people can reply on other clients it can be confusing currently.
and its part what comments make fun. 
<details>
<summary>see this for example</summary>
<p>
https://nostr-cooking.pages.dev/recipe/naddr1qqgxymmvdankuetnv5khxct4vdjj6q3qgnwpctdec0aa00hfy4lvadftu08ccs9677mr73h9ddv2zvw8fu9sxpqqqp65wr5sphh

https://redesign.nostr-cooking.pages.dev/recipe/naddr1qqgxymmvdankuetnv5khxct4vdjj6q3qgnwpctdec0aa00hfy4lvadftu08ccs9677mr73h9ddv2zvw8fu9sxpqqqp65wr5sphh
</p>
</details>  

Also to consider: Some pages like onboarding are not yet redesigned/implemented but are still in the codebase.
We should remove all nonsense from the codebase,
but I think onboarding also should be reimplemented in the redesign.

2024-03-21 17:08 UTC, chakany commented
@github-tijlxyz 
> I think it is important, its part of the nostr reply spec thing. And since people can reply on other clients it can be confusing currently. and its part what comments make fun.

Ok, fine.

> Also to consider: Some pages like onboarding are not yet redesigned/implemented but are still in the codebase. We should remove all nonsense from the codebase, but I think onboarding also should be reimplemented in the redesign.

We should consult with Karnage on what that would look like, though IMO using seed words is retarded.
Is there any way to get to onboarding right now? Don't want people to get redirected weirdly.

2024-03-22 19:35 UTC, github-tijlxyz commented on src/components/ZapModal.svelte
Zap modal needs to be fixed for mobile

2024-03-22 19:35 UTC, github-tijlxyz commented on src/routes/login/+page.svelte
> +    <Button class="self-center" primary={false}>Sign up</Button>
signup button currently does nothing, we need to implement onboard or at least link it somewhere where you can get more info about nostr or download a browser extention or something

2024-03-22 19:59 UTC, chakany commented on src/components/ZapModal.svelte
I already fixed it?

2024-03-22 20:09 UTC, chakany commented on src/routes/login/+page.svelte
> +    <Button class="self-center" primary={false}>Sign up</Button>
https://nostr.how/en/get-started

2024-03-22 23:36 UTC, github-tijlxyz approved these changes

2024-03-23 15:34 UTC, github-tijlxyz approved these changes

2024-03-23 15:36 UTC, merged